language: cpp
sudo: required
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc
      install: 
        - cmake --version
      script: 
        - cmake . -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF
        - make

    - os: linux
      compiler: gcc
      install: 
        - cmake --version
      script: 
        - cmake . -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF
        - make
        
    - os: windows
      install: 
        - cmake --version
      script: 
        - cmake.exe -G "Visual Studio 15 2017" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF -S .
        - cmake.exe --build . --config Debug
        - cmake.exe --build . --config Release
        
    - os: windows
      install: 
        - cmake --version
      script: 
        - cmake.exe -G "Visual Studio 15 2017" -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -S .
        - cmake.exe --build . --config Debug
        - cmake.exe --build . --config Release
        
    - os: osx
      osx_image: xcode11.3
      install: 
        - cmake --version
      script: 
        - cmake . -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF
        - make
        
    - os: osx
      osx_image: xcode11.3
      install: 
        - cmake --version
      script: 
        - cmake . -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF
        - make
        
notifications:
  email: false
