language: cpp
sudo: required
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc
      install: 
        - cmake --version
      script: 
        - cmake . -DBUILD_SHARED_LIBS=ON
        - make
        
    - os: linux
      compiler: gcc
      install: 
        - cmake --version
      script: 
        - cmake . -DBUILD_SHARED_LIBS=OFF
        - make

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
      before_install:
        - eval "${MATRIX_EVAL}"
      install: 
        - cmake --version
      script: 
        - cmake . -DBUILD_SHARED_LIBS=ON
        - make
        
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc7 && CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
      install: 
        - cmake --version
      script: 
        - cmake . -DBUILD_SHARED_LIBS=OFF
        - make

